name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: pmmp/setup-php-action@fa2accea978a84097cf40ecc7d46b2d71f258bd5
        with:
          php-version: "8.1"
          install-path: "${{ github.workspace }}/php"
          pm-version-major: "5"

      - name: Configure git for HTTPS
        run: git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Load Composer package cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/composer"
          key: "php-8.1-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-8.1-composer-"

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --no-progress

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: pmmp/setup-php-action@fa2accea978a84097cf40ecc7d46b2d71f258bd5
        with:
          php-version: "8.1"
          install-path: "${{ github.workspace }}/php"
          pm-version-major: "5"

      - name: Configure git for HTTPS
        run: git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Load Composer package cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/composer"
          key: "php-8.1-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-8.1-composer-"

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPUnit tests
        run: ${{ github.workspace }}/php/bin/php ./vendor/bin/phpunit --bootstrap vendor/autoload.php --fail-on-warning tests/phpunit
